name: Deploy to Coolify

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          curl -s -X GET \
            "http://37.59.238.227:8000/api/v1/deploy?uuid=w3yvu7nfs0ofrhts6gdecqra&force=false" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
